#!/bin/bash
# /etc/init.d/eastworld

### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Eastworld initscript
# Description: This Eastworld service
### END INIT INFO

case "$1" in
    start)
        echo "Starting Eastworld"
        /home/pi/Eastworld/start.py &
        ;;
    stop)
        echo "Stopping ledblink"
        #killall ledblink.py
        kill $(ps aux | grep -m 1 'python /home/pi/Eastworld/start.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service Eastworld start|stop"
        exit 1
        ;;
esac
exit 0