#!/bin/bash
# /etc/init.d/raspcar

### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Raspcar initscript
# Description: This service is used to start Raspcar
### END INIT INFO

case "$1" in
    start)
        echo "Starting Raspcar"
        mpc stop
        python /home/pi/Eastworld/start.py &
        ;;
    stop)
        echo "Stopping Raspcar"
        #killall start.py
        kill $(ps aux | grep -m 1 'python start.py' | awk '{ print $2 }')
        ;;
    *)
        echo "Usage: service Raspcar start|stop"
        exit 1
        ;;
esac
exit 0